version: '3'

services:
    db:
        build: ./requirements/mariadb/
        restart: always
    wordpress:
        build: ./requirements/wordpress/
        restart: always
        volumes:
          - wp_data:/home/data
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        networks:
          - nginx_network

    nginx:
        build: ./requirements/nginx/
        ports:
          - "8080:8080"
        restart: always
        networks:
          - nginx_network
        volumes:
          - wp_data:/home/data
networks:
    nginx_network:
        external: true

volumes:
    wp_data:
        driver: local
        driver_opts:
          type: none
          device: /home/zog/Inception/data
          o: bind
#    db_data: {}
