version: '3'

services:
    nginx:
        build: ./requirements/nginx/
        restart: always

services:
    db:
        build: ./requirements/db/
        restart: always

services:
    wordpress:
        build: ./requirements/wordpress/
        restart: always
