version: '3'

services:
    wordpress:
        build: ./requirements/wordpress/
        volumes:
            - /home/zog/Inception/srcs/data
        restart: always
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

    nginx:
        build: ./requirements/nginx/

          #        ports:
          #          - "443:443"
        restart: always

