version '3'

services:
    db:
        build: ./requirements/mariadb/Dockerfile
        volumes:
            - db_data: /home/melperri/data
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: password
            MARIA_DATABASE: wordpress
            MARIA_USER: wordpress
            MARIA_PASSWORD: wordpress

services:
    wordpress:
        depends_on:
            - db
        build: ./requirements/wordpress/Dockerfile
        ports:
            - "443:443"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress

services:
    depends_on:
        - wordpress
    nginx:
        build: ./requirements/nginx/Dockerfile
        ports:
            - "443:443"
        restart: always

volumes:
    db_data: {}
